# Generated by Django 5.0.6 on 2024-07-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, max_length=200)),
                ('team_status', models.CharField(blank=True, max_length=200)),
                ('team_size', models.CharField(blank=True, max_length=200)),
                ('company_size', models.CharField(blank=True, max_length=200)),
                ('weekly_hours', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('dev_type', models.CharField(blank=True, max_length=200)),
                ('development_type', models.CharField(blank=True, max_length=200)),
                ('project_tools', models.CharField(blank=True, max_length=200)),
                ('agile_methods', models.CharField(blank=True, max_length=200)),
                ('job_satisfaction', models.CharField(blank=True, max_length=200)),
                ('job_stress', models.CharField(blank=True, max_length=200)),
                ('work_life_balance', models.CharField(blank=True, max_length=200)),
                ('job_motivation', models.CharField(blank=True, max_length=200)),
                ('professional_goal', models.CharField(blank=True, max_length=200)),
                ('sport_activity', models.CharField(blank=True, max_length=200)),
                ('main_sport', models.CharField(blank=True, max_length=200)),
                ('favorite_sport', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
